apiVersion: v1
kind: Service
metadata:
    name: backend
    labels:
        group: example
spec:
    selector:
        app: second-app
    ports:
        - protocol: 'TCP'
          port: 80 #external
          targetPort: 80 #inside the container
    type: LoadBalancer