version: "3"
services:
  auth:
    build: ./auth-api
  users:
    build: ./users-api
    ports: 
      - "8080:8080"
    environment:
      AUTH_ADDRESS: auth
  tasks:
    build: ./tasks-api
    ports: 
      - "8000:8000"
    environment:
      TASKS_FOLDER: tasks
      AUTH_ADDRESS: auth
    volumes:
      - /app/tasks
  frontend:
    build: ./frontend
    ports:
      - "80:80"