apiVersion: apps/v1
kind: Deployment
metadata:
    name: auth-deployment
spec: 
    replicas: 1
    selector:
        matchLabels:
            app: auth 
    template:
        metadata:
            labels:
                app: auth
        spec:
            containers:
            - name: auth
              image: benjaminshinar/kub-network_auth:0.1