apiVersion: apps/v1
kind: Deployment
metadata:
    name: users-deployment
spec: 
    replicas: 1
    selector:
        matchLabels:
            app: users 
    template:
        metadata:
            labels:
                app: users
        spec:
            containers:
            - name: users
              image: benjaminshinar/kub-network_users:0.4
              env:
              - name: AUTH_ADDRESS
                value: localhost
            # - name: auth
            #   image: benjaminshinar/kub-network_auth:0.1