apiVersion: v1
kind: Service
metadata:
    name: story-service
spec:
    selector:
        app: story
    ports:
        - protocol: 'TCP'
          port: 80 #external
          targetPort: 3000 #inside the container
    type: LoadBalancer